### ISSUE TITLE
Resultant Apple News JSON creates errors when POSTing to create article

### ISSUE THREAD

**Issue by jchristn** [micnews/distro#60]
Hi, first off thanks for creating this awesome service!  I passed an HTML article to your API and successfully received a response.  

However, when I POST this to Apple News (/channels/{channelId}/articles) I get back a series of INVALID_DOCUMENT errors, one for each component, stating that 
```
Component layout with identifier, bodyLayout, not found.
```

I tried using Apple News Preview locally and encountered a similar set of errors:
```
Error: Component layout with identifier, bodyLayout, not found.
components -> 0 -> layout
```

Also, the JSON returned by your service has the top-level key named as 'article' where really what the service returns (at least for my article) is a series of components.

Perhaps I'm missing something?  Thanks!

**Comment by jchristn** [comment]
Hi all, any feedback on this?  Thanks

**Comment by ellell** [comment]
@jchristn Hey, sorry for the delay we're looking into it!

**Comment by iefserge** [comment]
@jchristn Hi sorry for the delay!

Service returns only a part of the document, Apple News components for the actual article content. They can be embedded into the article, structured like https://github.com/micnews/article-json-to-apple-news/blob/master/lib/index.js#L22

This allows resulting document to be customized with custom colors, header, byline etc.

Apple docs
https://developer.apple.com/library/content/documentation/General/Conceptual/Apple_News_Format_Ref/Properties.html

**Comment by jchristn** [comment]
Hi @ellell and @iefserge - yes - my code takes the returned dictionary { articles: [ ... ] }, renames articles to components, and embeds it as a key-value pair into another object of the form: 
```
{
  language: "",
  title: "",
  version: "",
  identifier: "",
  author: { ... },
  layout: { ... },
  components: [ ... ]   <-- body from your service here
}
```
The only errors returned from my POST request to Apple News to create the article after I embed into the outer dictionary are with the layout you return in the body of each component, called ```bodyLayout```.  Do I need to supply a definition for this or am I missing something?

**Comment by iefserge** [comment]
Yeah, there are styles that need to be added, for example default ones https://github.com/micnews/article-json-to-apple-news/blob/master/lib/default-styles.js

**Comment by jchristn** [comment]
Ah, I see.  I'll look into how I embed these into my JSON and report back if I have issues.  

Is this something that you're considering adding into the default response from your conversion API?

Thanks!

**Comment by jchristn** [comment]
Update: will be testing this today and tomorrow, will close the issue out if it solved my problem.  Thanks again for getting back to me.

**Comment by jchristn** [comment]
Thanks, this fixed my issue!
