### ISSUE TITLE
Not embedding Youtube links contained within iframes

### ISSUE THREAD

**Issue by jchristn** [micnews/distro#61]
Service is not adding embedded web videos for Youtube links contained within iframe.

Source HTML submitted to service: https://gist.github.com/jchristn/168ea187db01f2019d9b353838e32acf

Response from service (encapsulated into the object I submit to Apple News): https://gist.github.com/jchristn/e002b6349f9b8625e8ef72cb15f86d68

Apple News returns success but the article of course does not have videos.

**Comment by jchristn** [comment]
Hi all, any chance iframes are supported for embedding youtube videos?

**Comment by iefserge** [comment]
@jchristn Embeds within paragraphs aren't supported by the article format. They must be at the top level outside of the `<p>` tag.

**Comment by jchristn** [comment]
I see.  Are you planning to amend your parser to make these elements sequential?  Seems like a monumental task to try and get people to structure their HTML in such a rigid manner.  Otherwise, it seems your service only handles HTML when it's organized in a very specific way.  Let me know.  Thanks!

**Comment by iefserge** [comment]
There is no goal to handle arbitrary HTML, only "article" HTML -- list of formatted paragraphs with embeds in between. This format makes it easy to convert to FBIA, Apple News articles.
What's the use case for embeds in paragraphs?

**Comment by jchristn** [comment]
Hi @iefserge I was hoping to take any HTML and have the parser serialize the entries into a sequential list, removing the embedding.  Most of the WYSIWYG editors out there have embeds not by design but as a biproduct of not having been designed to output article HTML.  Should I assume your service will not be capable of doing this or is this something you plan to address?  Thanks!

**Comment by iefserge** [comment]
Probably not any time soon, service doesn't try to fix inputted html, though we should be able to highlight these cases as errors. How would you like embeds in paragraphs to be represented in the resulting Apple News document?

**Comment by jchristn** [comment]
I wouldn't necessarily consider it to be "fixing" input HTML but rather supporting it in a reasonable way.  

For embedded content, I would hope/expect the output of your service to just be that the nested/embedded content would be the next component returned in the array, i.e.:
```
<p>this is some text<img src="foo" /></p>
```
becomes
```
[
  ...
  { role: "blah", text: "this is some text", ... },
  { role: "image", text: "foo", ... }
]
```

That would at least allow it to be useful for HTML that was designed specifically in the way your service expects, even if the output was consistent with the input HTML.

Thanks!
Joel
